### ISSUE TITLE
Is the service down? Im getting a 503 and xhr.statusCode = 0 was returned. 

### ISSUE THREAD

**Issue by glenskie16** [microsoft/code-push#665] opened 2019-10-06 18:00 UTC
Hello, is the service currently down ?

**Comment by yaronlevi** [comment] 2019-10-07 12:51
Yes... the service is down!
Please update the AppCenter's status page.

**Comment by ronilitman** [comment] 2019-10-07 13:15
Any update?

**Comment by alexandergoncharov** [comment] 2019-10-07 13:18
Hi @glenskie16 and @yaronlevi,
Thanks for reporting!

Could you please share your versions of plugins?

**Comment by ronilitman** [comment] 2019-10-07 13:21
@alexandergoncharov I am using react native code push 5.3.2. I don't think it's related to react native at all. I, for example, get 503 when trying to call to CodePush.checkForUpdate. I am expecting to get null if there is no update, and object if there is update. I got none.

**Comment by absoutherland** [comment] 2019-10-07 14:13
Also having this issue

**Comment by stumpc** [comment] 2019-10-07 14:18
Also having this issue.

**Comment by digital-tcbs** [comment] 2019-10-07 14:23
Also having this issue with cordova code-push. And when user can update app, appcenter dont update active user, install or download. API return 500 internal error.

**Comment by dogcity** [comment] 2019-10-07 14:24
Also having this issue.

**Comment by ButchMonkey** [comment] 2019-10-07 14:34
This is happening too frequently recently and causing major issues for us. 
Why is the updatecheck not hosted with the rest of the appcenter api?
Can we have access to the source for the updatecheck to self host and monitor issues ourselves?

**Comment by bberzinskas-tw** [comment] 2019-10-07 14:38
Also having issues with this.   This is introducing app init delays in the minutes!

**Comment by ButchMonkey** [comment] 2019-10-07 14:51
This called all be done inside of the codepush code.
As long as you know the packagehash, deployment key and maybe the label. You would just need to call the API and get all the updates for the deployment and then find the one that you need to download.

**Comment by yaronlevi** [comment] 2019-10-07 15:09
This is critical.
I think the engineering team should be more transparent about those issues.
They have a serious impact on our business.
If the community will get more insights about what's happening at your end, maybe we can better help pinpoint the problem.

**Comment by mcrichards** [comment] 2019-10-07 15:20
@alexandergoncharov - Can you update us please? Your status site does not indicate any issue, but your service has introduced app load times of 2-3 minutes for our users.

**Comment by decadX** [comment] 2019-10-07 15:36
503 error, the app pool down? This should be on the monitoring service. 

https://codepush.azurewebsites.net/

**Comment by yuri-kulikov** [comment] 2019-10-07 15:48
Hi all,

Sorry for this. We are investigating the issue right now. The problem is related to the acquisition service (the part which is used by SDK), the management service (CLI/App Center portal) is working fine.
We expect this issue to be resolved within a few hours or less. In case of any changes we will let you know.

**Comment by ronilitman** [comment] 2019-10-07 15:51
@yuri-kulikov Thank you for your response. is there any status site that we can monitor to see when this will be resolved?

**Comment by ozzstrich** [comment] 2019-10-07 15:59
FYI this was heavily affecting our test suite so for now we've changed `checkFrequency` from `.ON_APP_START` to `.MANUAL` and it's working fine.

**Comment by dogcity** [comment] 2019-10-07 16:28
We continue with the problem, we use react-native, approximately 5 minutes of waiting for the API response

**Comment by yuri-kulikov** [comment] 2019-10-07 16:32
@ronilitman Sorry for the long wait, the status page is updated.

**Comment by ronilitman** [comment] 2019-10-07 18:09
@yuri-kulikov it starts to look good on my side, can we officially say that it's behind us? Im in the middle of a deploy to the App Stores 😆

**Comment by yuri-kulikov** [comment] 2019-10-07 18:14
It looks like the main issue is resolved! 🎉 
Once again, we apologize for the inconvenience. We will continue to monitor the service.

**Closed** 2020-02-04 01:03 UTC
