### ISSUE TITLE
Losing deployment after Application is "swiped up"

### ISSUE THREAD

**Issue by jlebensold** [Microsoft/code-push#114] opened 2016-01-21 13:36 UTC
Hi there,

When I run CodePush's example app and I do an update, the update runs successfully on resume. However, if I swipe up and close the app, the build reverts to the one that was shipped with the binary. Is this by design? I can't get the build to stick after shutdown.

Thanks!

**Comment by lostintangent** [comment] 2016-01-21 15:12
Hey @jlebensold! This sounds like our rollback protection feature thinking that the update failed and rolling you back. Which sample are you trying? React Native or Cordova?

**Comment by jlebensold** [comment] 2016-01-21 15:37
Hi Jonathan! Thanks for the quick response :)

I'm trying the react native app on iOS

**Comment by lostintangent** [comment] 2016-01-21 15:44
OK let me look into the sample to see if it's doing something wrong. The behavior you are seeing is not by design unless he update includes a crash while starting up. We do that rollback on the client side to make sure end users aren't ever blocked if a broken update is accidentally released to CodePush. But a non-broken release should obviously not be rolled back :)

Sorry for the confusion, and I'll let you know the issue as soon as I get in the office this morning and check it out (I'm on Pacific time).

**Comment by jlebensold** [comment] 2016-01-21 16:45
Thanks Jonathan! I can work through it with you over twitter / email / skype if necessary

**Comment by geof90** [comment] 2016-01-21 21:09
Hi @jlebensold

The behaviour you are seeing is expected behaviour. The way rollback protection works is that we rely on a call to `notifyApplicationReady()` or `sync()` (which calls `notifyApplicationReady()` internally) to signal that a update has been applied successfully. Otherwise, when the app process is killed and restarted, during the next boot up the plugin will detect that in the update that `notifyApplictionReady()` was not called in the update that was last applied, and therefore trigger a rollback.

In a typical application, `snyc()` or `notifyApplictionReady()` API will be called automatically during the `componentDidMount()` React component lifecycle event. The sample app is slightly different in that, `sync()` is only called when the "sync" button is pressed. Therefore, after an update is applied, you need to press the "sync" button again in order to get the update to stick. The reason why the sample app was (perhaps a bit oddly) designed as such is so that we can easily do a manual test of the rollback feature by putting the call to `notifyApplicationReady()` in a button press so that the user can manually confirm the update. Again, in a typical application, if you put the call to `sync()` or `notifiyApplictionReady()` inside `componentDidMount()`, you should see updates stick around without having the user perform any manual action, which is probably the expected behaviour for most applictions.

**Comment by lostintangent** [comment] 2016-01-21 22:55
@jlebensold So long story short, the sample app is setup to do the behavior you are seeing. If you create an app using CodePush, you won't see this behavior if your app calls `sync` on startup. If your app doesn't call `sync` on startup (e.g. in a  button click, timer), then you simply need to call `notifyApplicationReady` in startup, to notify the CodePush runtime that you consider the update successful.

**Comment by jlebensold** [comment] 2016-01-22 08:52
@lostintangent @geof90 thanks guys! You've just made my day!

**Comment by lostintangent** [comment] 2016-01-22 15:13
Yay! Thanks for confirming that this worked :) I'm going to close this bug and we'll track the sample fix on the React Native repo.

**Closed by lostintangent** 2016-01-22 15:13 UTC
