### ISSUE TITLE
Trying to install and sync causes crash. Latest Code Push

### ISSUE THREAD

**Issue by northkode** [Microsoft/code-push#583] opened 2018-08-08 17:50 UTC
Thanks so much for filing an issue or feature request! We will address it as soon as we can. Please follow these guidelines:

Using the latest code push.. I am getting this error on a REAL ipad Device when trying to sync

```File Transfer Download success
=================================================================
Main Thread Checker: UI API called on a background thread: -[WKWebView loadFileURL:allowingReadAccessToURL:]
PID: 297, TID: 28807, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   App                           0x00000001042d6924 -[CDVWKWebViewEngine loadRequest:] + 372
5   App                           0x00000001042e9a24 -[CodePush loadURL:] + 156
6   App                           0x00000001042e9924 -[CodePush loadPackage:] + 120
7   App                           0x00000001042e75ac __20-[CodePush install:]_block_invoke + 660
8   libdispatch.dylib                   0x000000010520d260 _dispatch_call_block_and_release + 24
9   libdispatch.dylib                   0x000000010520d220 _dispatch_client_callout + 16
10  libdispatch.dylib                   0x0000000105219284 _dispatch_queue_override_invoke + 968
11  libdispatch.dylib                   0x000000010521e84c _dispatch_root_queue_drain + 604
12  libdispatch.dylib                   0x000000010521e584 _dispatch_worker_thread3 + 136
13  libsystem_pthread.dylib             0x0000000185607fac _pthread_wqthread + 1176
14  libsystem_pthread.dylib             0x0000000185607b08 start_wqthread + 4
2018-08-08 11:39:40.673427-0600 App[297:28807] [reports] Main Thread Checker: UI API called on a background thread: -[WKWebView loadFileURL:allowingReadAccessToURL:]
PID: 297, TID: 28807, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 21
Backtrace:
4   App                           0x00000001042d6924 -[CDVWKWebViewEngine loadRequest:] + 372
5   App                           0x00000001042e9a24 -[CodePush loadURL:] + 156
6   App                           0x00000001042e9924 -[CodePush loadPackage:] + 120
7   App                           0x00000001042e75ac __20-[CodePush install:]_block_invoke + 660
8   libdispatch.dylib                   0x000000010520d260 _dispatch_call_block_and_release + 24
9   libdispatch.dylib                   0x000000010520d220 _dispatch_client_callout + 16
10  libdispatch.dylib                   0x0000000105219284 _dispatch_queue_override_invoke + 968
11  libdispatch.dylib                   0x000000010521e84c _dispatch_root_queue_drain + 604
12  libdispatch.dylib                   0x000000010521e584 _dispatch_worker_thread3 + 136
13  libsystem_pthread.dylib             0x0000000185607fac _pthread_wqthread + 1176
14  libsystem_pthread.dylib             0x0000000185607b08 start_wqthread + 4
2018-08-08 11:39:40.815324-0600 App[297:28759] Failed to load webpage with error: The operation couldn’t be completed. (kCFErrorDomainCFNetwork error 1.)```

and the application never updates. This does not happen on the simulator

**Comment by alexandergoncharov** [comment] 2018-08-10 12:51
Hi @northkode ,
Thanks for reporting!

It is looks like this Cordova issue: https://github.com/Microsoft/cordova-plugin-code-push/issues/424

If you use clear Cordova with WkWebView plugin you can use work around which provided in that issue. Fix for this issue in repo will be soon as it should be improved.

If you have other env or you have something to add could you please provide it in that issue to keep all info about this issue in one place. https://github.com/Microsoft/cordova-plugin-code-push/issues/424

Also, I'm going to close this issue as this is duplicate of https://github.com/Microsoft/cordova-plugin-code-push/issues/424

Please let me know if you any questions.

Thanks,
Alexander

**Closed by alexandergoncharov** 2018-08-10 12:51 UTC
