### ISSUE TITLE
Investigate reasons for rollback with code-push-cli?

### ISSUE THREAD

**Issue by pke** [Microsoft/code-push#258] opened 2016-06-15 09:27 UTC
Is there a way to check the reasons for a rollback in the code-push command line?
We have no logs stored on the devices and have no way to find out why one device updated successfully and another performed a rollback.

**Comment by lostintangent** [comment] 2016-06-15 23:22
Closing this is a duplicate of https://github.com/Microsoft/cordova-plugin-code-push/issues/140

**Closed by lostintangent** 2016-06-15 23:22 UTC
