### ISSUE TITLE
release-react does not detect Info.plist changes

### ISSUE THREAD

**Issue by sewil** [microsoft/code-push#705] opened 2020-02-19 13:36 UTC
Changes in Info.plist are not detected and prompts the error `The uploaded package was not released because it is identical to the contents of the specified deployment's current release.`. I changed the `CodePushDeploymentKey` in Info.plist.

```
$ code-push -v
2.1.9
```

**Comment by alexandergoncharov** [comment] 2020-03-04 13:46
Hi @sewil ,
Thanks for reporting

Yeah, I reproduced your issue. Thanks.
We'll investigate it and will keep you updated.

Also, just a note: `code-push` cli is deprecated. Our recommendation is using appcenter cli: https://github.com/microsoft/appcenter-cli

**Comment by alexandergoncharov** [comment] 2020-03-04 15:20
Oh, sorry, I misinform you. It is correct behavior because CodePush can't update a native part of the app. It can update just the JS part and assets.
So, It isn't possible to update`info.plist` with CodePush unfortunately. You have to make a new binary update.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions.

**Closed by alexandergoncharov** 2020-03-04 15:20 UTC
Labels: investigating
