### ISSUE TITLE
code-push release-react Cannot assign to read only property '0' of object '[object String]'

### ISSUE THREAD

**Issue by amesf** [Microsoft/code-push#420] opened 2017-03-19 23:25 UTC
CLI v1.12.9-beta throws error on android:

Detecting android app version:

/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:28
		to[key] = val;
		        ^

TypeError: Cannot assign to read only property '0' of object '[object String]'
    at assignKey (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:28:11)
    at assign (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:43:4)
    at assignKey (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:30:13)
    at assign (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:43:4)
    at deepAssign (/usr/local/lib/node_modules/code-push-cli/node_modules/deep-assign/index.js:64:3)
    at deepParse (/usr/local/lib/node_modules/code-push-cli/node_modules/gradle-to-js/lib/parser.js:135:27)
    at deepParse (/usr/local/lib/node_modules/code-push-cli/node_modules/gradle-to-js/lib/parser.js:137:27)
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/code-push-cli/node_modules/gradle-to-js/lib/parser.js:392:13)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ReadStream.Readable.push (_stream_readable.js:134:10)
    at onread (fs.js:1939:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:628:17)

I am able to build on CLI v1.12.6-beta without problem.

my react-native envionments:
    "react": "15.4.2",
    "react-native": "^0.42.0",
    "react-native-code-push": "^1.17.2-beta",

**Comment by max-mironov** [comment] 2017-03-20 10:40
Hi @amesf, that looks interesting, 
Is it possible for you to share with us your `build.gradle` file from android/app folder so that we can try to reproduce your issue (or may be you have the minimum app example where we can try to reproduce this)?

**Comment by max-mironov** [comment] 2017-03-27 05:18
@amesf - hi, do you have a chance to look at this?

**Comment by max-mironov** [comment] 2017-04-03 05:18
@amesf - we are closing the issue for now, please let us know if you get I chance to look at this and the issue is still reproducing on your side.

**Closed by max-mironov** 2017-04-03 05:18 UTC
Labels: waiting-for-clarification

**Comment by the-simian** [comment] 2017-04-09 06:00
i am also having this exact issue, but since i cannot reopen this I'll simply submit a new issue.
