### ISSUE TITLE
About appStoreVersion property?

### ISSUE THREAD

**Issue by TanTan-TT** [Microsoft/code-push#50] opened 2015-11-07 05:02 UTC
Hi
    About appStoreVersion, it confused me a lot. I did some test. Following is steps

1. make my App's version is 1.0.0
2. upload a js package which need version 2.0.0
3. open my App, upgrade alert is shown

So in my mind, it should not have alert shown because my uploaded js package needs one App which version is 2.0.0. Is it right?

**Comment by lostintangent** [comment] 2015-11-07 07:50
Yep, that is correct. You definitely shouldn't have seen that update notification. When the update check is made to the service, it explicitly ignores any releases which are specified for versions that are newer or older that what you are already running.

Could you give a sample of the code you added to your app as well as the exact release command you used from the CLI?

**Comment by geof90** [comment] 2015-11-07 08:02
Confirmed that this is a bug. Closing this issue and tracking it in the react native repo https://github.com/Microsoft/react-native-code-push/issues/39 since it rightfully belongs there.

**Closed by geof90** 2015-11-07 08:02 UTC
