### ISSUE TITLE
React Native iOS app only updates if release is marked as 'mandatory'

### ISSUE THREAD

**Issue by mikeislearning** [microsoft/code-push#672] opened 2019-11-04 19:01 UTC
react: 16.9.0
react-native: 0.61.2
react-native-code-push: 5.7.0

Whenever we release a new codepush build, it'll update Android without a problem, but for iOS, we've had to mark it as mandatory for the update to actually take effect. Otherwise the iOS app will indicate the newest version has been installed, but it won't actually reflect the changes. If we mark it as mandatory after that happens, it will also fail because the app thinks it is using the latest version.

Any thoughts?

**Comment by nol13** [comment] 2019-11-20 17:42
Interestingly, this is seems to only be happening for us on the Production deployment, Staging deployment not having this issue.

react-native: 0.59.8
react-native-code-push: 5.5.0

**Comment by cdriscol** [comment] 2019-11-20 21:36
@mikeislearning @nol13  - one thing to check that bit us, is when you do the RN upgrade using something like https://github.com/react-native-community/rn-diff-purge is to make sure your `AppDelegate.m` still has the appropriate CodePush code in there.  Just something to check, especially if only your iOS build is effected.

**Comment by nol13** [comment] 2019-11-20 21:58
@cdriscol ya not 100% if we used rn-diff-purge, but the codepush code definitely got removed from AppDelagate.m during our last upgrade, ty!

am told it was android too, and still not sure why the build that used the staging deploy key would have still worked, but tbh haven't seen the issue first hand either though so..

**Comment by alexandergoncharov** [comment] 2020-03-03 15:21
Hi @mikeislearning and @nol13 ,
Thanks for reporting!

Unfortunately, I can't reproduce it. Could you please provide more detailed repro steps?

> this is seems to only be happening for us on the Production deployment, Staging deployment not having this issue.

It is really strange because the only difference between them is the name. You can also create more deployments with any names.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or when you provide more detailed repro steps.

**Closed by alexandergoncharov** 2020-03-03 15:21 UTC

**Comment by nol13** [comment] 2020-03-03 16:15
@alexandergoncharov thanks for looking. I'm guessing it was just something we messed up during the upgrade. I'm now off the project though and haven't touched this in a while.
