### ISSUE TITLE
How have all users update to latest version

### ISSUE THREAD

**Issue by rochestb** [Microsoft/code-push#335] opened 2016-10-14 15:38 UTC
Hello,

I have users on a variety of versions and I need them all to be updated to the latest roll out (2.1). From what I can tell when I look at the history is that our of 12k users, none of them have or are able to update the latest version. (Active: 0% (0 of 12,409)   Total: 0 (1 pending) ). Do I need to target binaries and specify which version they should update to? 

`$ code-push release-react myApp ios *`
`$ code-push promote myApp Staging Production`

I'm having a hard time understanding how my rollouts affect users on different versions. 

I am on 1.12.3-beta

**Comment by rgerd** [comment] 2017-01-11 22:47
Have you tried using the `--mandatory` flag?
https://microsoft.github.io/code-push/docs/cli.html#releasing-updates-general

**Comment by orlando** [comment] 2017-01-12 21:36
Facing this problem too, If we use a range it doesn't update. But if we target the specific version then the update goes through

**Comment by patrickomeara** [comment] 2017-01-13 04:15
@orlando I have a similar issue how are you targeting the specific version?

**Comment by orlando** [comment] 2017-01-13 13:23
@patrickomeara so the issue is not a code-push issue, is how node-semver works. Ranges only works for non pre-release versions. https://github.com/npm/node-semver#prerelease-tags

> For example, the range >1.2.3-alpha.3 would be allowed to match the version 1.2.3-alpha.7, but it would not be satisfied by 3.4.5-alpha.9, even though 3.4.5-alpha.9 is technically "greater than" 1.2.3-alpha.3 according to the SemVer sort rules. The version range only accepts prerelease tags on the 1.2.3 version. The version 3.4.5 would satisfy the range, because it does not have a prerelease flag, and 3.4.5 is greater than 1.2.3-alpha.7.
>
>The purpose for this behavior is twofold. First, prerelease versions frequently are updated very quickly, and contain many breaking changes that are (by the author's design) not yet fit for public consumption. Therefore, by default, they are excluded from range matching semantics.

So what I did is removing our prerelease tags from our staging environment and just using the same version syntax as production

**Comment by sergey-akhalkov** [comment] 2017-02-22 07:42
@orlando, @patrickomeara, please let me know if I could help of if the issue was resolved.

**Comment by orlando** [comment] 2017-02-22 14:37
@sergey-akhalkov no problem here, is the expected behaviour of node-semver. What we need to do maybe is to put a reference in the code-push documentation

**Comment by sergey-akhalkov** [comment] 2017-02-27 13:17
@orlando, got it, thank you, I'll update docs to make this more clear.

**Comment by sergey-akhalkov** [comment] 2017-02-28 08:29
Closing this due to #405 has been merged.

**Closed by sergey-akhalkov** 2017-02-28 08:29 UTC
Labels: question
