### ISSUE TITLE
The provided resource is too large

### ISSUE THREAD

**Issue by notlose** [Microsoft/code-push#139] opened 2016-02-22 07:09 UTC
error message "The provided resource is too large" shown when i code-push release to staging
and i cannot found size limit info in documentation.

**Comment by notlose** [comment] 2016-02-22 07:11
and i checked my assets folder size is only 2.6MB

**Comment by notlose** [comment] 2016-02-22 09:11
problem resolved

**Comment by Almouro** [comment] 2016-02-22 17:25
@notlose How did you solve it? I just ran into this problem...

**Comment by notlose** [comment] 2016-02-22 17:46
I dropped email to them, and they helped me out with some temporary fix. They told me they will have solution for this problem tomorrow.

從 Outlook Mobile 傳送




On Mon, Feb 22, 2016 at 9:25 AM -0800, "Alexandre Moureaux" <notifications@github.com> wrote:





@notlose How did you solve it? I just ran into this problem...

---

**Comment by lostintangent** [comment] 2016-02-22 18:09
Hey @almouro, send an email to codepushfeed@microsoft.com with your app name and deployment name and we'll fix you up. We have a bug that we just discovered when the release history gets too long. Where addressing the root of the problem, but we can unblock you in the meantime.

I'm reopening this issue since it hasn't actually been fixed.

**Comment by silhouettes** [comment] 2016-02-23 00:29
@Almouro: We've just deployed a hotfix for this issue. Can you confirm that the problem is resolved for you?

I will close this issue in the meantime, as it should no longer affect users.

**Closed by silhouettes** 2016-02-23 00:29 UTC

**Comment by Almouro** [comment] 2016-02-23 10:33
@silhouettes @lostintangent just tried it and it works! Thanks guys! :)

**Comment by lostintangent** [comment] 2016-02-23 16:42
@almouro Thanks for being patient while we address that bug!

**Comment by Almouro** [comment] 2016-02-23 19:57
@lostintangent 
1. Thank you for this amazing free tool :)
2. You got it fixed while I was sleeping here in France, so no patience actually required :)
