### ISSUE TITLE
Use the CodePush Management SDK inside electron

### ISSUE THREAD

**Issue by wilomgfx** [Microsoft/code-push#433] opened 2017-04-24 16:33 UTC
I am just wondering if its possible to use the CodePush Management SDK within electron/node-webkit.

Im looking to build a GUI application to manage code-push enabled apps. I know i could use the cli, but as i saw the SDK, it made no sense to call the cli for each commands.

Unfortunately, when i ``` import CodePush from 'code-push'; ``` from my electron app( using webpack2) i get this error : 

> Uncaught TypeError: require is not a function
>     at Object../node_modules/formidable/lib/incoming_form.js (incoming_form.js:3)
>     at __webpack_require__ (bootstrap e7cce0a…:657)
>     at fn (bootstrap e7cce0a…:85)
>     at Object../node_modules/formidable/lib/index.js (index.js:1)
>     at __webpack_require__ (bootstrap e7cce0a…:657)
>     at fn (bootstrap e7cce0a…:85)
>     at Object../node_modules/superagent/lib/node/index.js (index.js:7)
>     at __webpack_require__ (bootstrap e7cce0a…:657)
>     at fn (bootstrap e7cce0a…:85)
>     at Object../node_modules/code-push/script/management-sdk.js (management-sdk.js:6) 

Which makes me think it is not usable with something other than node directly. Maybe im wrong, but i've looked into resolving the issue and could not find a solution! Thanks :)

**Comment by sergey-akhalkov** [comment] 2017-04-25 10:11
Hi @wilomgfx, thanks for reaching us. As of now, it is not possible to use CodePush with Electron due to both CodePush SDK's (React Native module for CodePush and Cordova plugin for CodePush) are using native-side code (Java and Objective-C) to handle platform (Android and iOS) specific operations such as download update, unzip archive, copy/delete files and etc. To make things work, it is probably needed to implement CodePush SDK using JS or try to adapt Java module to use it further with Electron.
I have not heard any plans regarding to support Electron (we probably need to discuss it), as of now, we are   working on other high priory tasks such us "Code signing" and "Support brownfield React Native apps" features.

**Comment by wilomgfx** [comment] 2017-04-25 12:48
Hi thank you for your response. I am aware that code-push uses native code for ios and android, but i was talking about the [management SDK](https://github.com/Microsoft/code-push/tree/master/sdk). Which is purely in Typescript.
I tried using it under node and it worked fine, but under an electron environnement with webpack, i was not able to make it work, i kept getting the error mentioned above.

(I updated the issue's title, sorry if it was misleading)

**Comment by sergey-akhalkov** [comment] 2017-04-27 08:12
Hi @wilomgfx, thanks for the clarification. It's hard to say for me what actually went wrong here, due to we have not faced with such kind of CodePush using specific scenarios before. Is it possible if you have the same problem as [here](https://github.com/webpack/webpack/issues/1697)? I could probably try to help you if you provide me with your webpack configuration.

**Comment by wilomgfx** [comment] 2017-04-27 12:39
Hi @sergey-akhalkov , my repo is public and here is my dev webpack config file
https://github.com/wilomgfx/code-push-gui/blob/master/webpack.config.renderer.dev.js

Thanks :)!

**Comment by sergey-akhalkov** [comment] 2017-04-27 12:55
@wilomgfx, got it, I'll quickly look at it and let you know if I'll find out the root cause of the issue. Please also let me know if you'll also find out the way to resolve the issue.

**Comment by wilomgfx** [comment] 2017-04-27 13:17
@sergey-akhalkov  thank you! If i fix, ill post here for sure.

**Comment by sergey-akhalkov** [comment] 2017-05-15 13:08
Hi @wilomgfx, do you still experiencing the issue?

**Comment by wilomgfx** [comment] 2017-05-16 23:16
Hi @sergey-akhalkov i haven't tried again. I switched to another urgent project. But if i ever find out why... il post here. Should be looking into that by the end of this month.

**Comment by sergey-akhalkov** [comment] 2017-05-22 11:50
Hi @wilomgfx, got it, so I'm closing this for now, please let me know if any updates or feel free to reopen if needed.

**Closed by sergey-akhalkov** 2017-05-22 11:50 UTC
Labels: enhancement

**Comment by tudiantuan** [comment] 2020-11-20 07:34
I develop app electron. Can anybody help me with an example of electron codepush?
