### ISSUE TITLE
CodePush downloads prior version for patch binary release

### ISSUE THREAD

**Issue by newyankeecodeshop** [Microsoft/code-push#504] opened 2017-09-05 14:12 UTC
We are using `code-push-cli@2.0.2-beta`.

We have a React Native application using CodePush. The CodePush server is not obeying the documentation regarding minor versions and patch versions. We have deployed code for a version `2.3`. According to the documentation:

> NOTE: If the app store version in the metadata files are missing a patch version, e.g. 2.0, it will be treated as having a patch version of 0, i.e. 2.0 -> 2.0.0. The same is true for app store version equal to plain integer number, 1 will be treated as 1.0.0 in this case.

However, when we deployed (via TestFlight) a new version of the app `2.3.1`, the CodePush server was returning the latest production 2.3 release as an appropriate (and mandatory) install for the 2.3.1 binary. This code is not compatible with binary module changes, and the app crashes.

Why is the server returning a 2.3 CodePush bundle as appropriate for a 2.3.1 binary?
Also, why does CodePush not notice that the binary bundle is newer than the downloaded CodePush bundle? It could at least use the binary JS bundle until a newer bundle is distributed via CodePush?

This is the URL that React Native CodePush is using:

> https://codepush.azurewebsites.net/updateCheck?deploymentKey=XXX&appVersion=2.3.1&packageHash=&isCompanion=&label=&clientUniqueId=XXX

and the response from the server is:

`{"updateInfo":{"downloadURL":"https://codepush.blob.core.windows.net/storagev2/XXX","description":"","isAvailable":true,"isMandatory":true,"appVersion":"2.3.1","packageHash":"XXX","label":"v64","packageSize":5712758,"updateAppVersion":false,"shouldRunBinaryVersion":false}}`

The above package (v64) was published with an App Version of "2.3".

We request that the CodePush behavior be changed as the documentation describes, or a mechanism be provided to allow us to control whether we want CodePush bundles when the binary versions differ.

**Comment by sergey-akhalkov** [comment] 2017-09-05 14:25
Hi @newyankeecodeshop, thanks for reaching us.

Could you please confirm if the issue you have is the same as here https://github.com/Microsoft/code-push/issues/400#issuecomment-281279417

If so, the behaviour you are experiencing is not the issue at all - it is how semver works. Probably we should add some notes about this in docs to avoid confusion in future.

To fix the issue you can patch your release `targetBinaryVersion` from 2.3 to 2.3.0

Please let me know if you have any questions.

**Comment by newyankeecodeshop** [comment] 2017-09-05 15:40
Yes @sergey-akhalkov that is the same issue. I see that is how semver works, but why doesn't the CodePush server convert `2.3` to `2.3.0` before passing the value to the semver logic? That is what your documentation says and also is a more appropriate behavior for CodePush, don't you think? As your documentation also states, a semver range expression can be used, so if the developer's intent is to have a bundle apply to all patch versions of a binary, it can be expressed explicitly.

**Comment by sergey-akhalkov** [comment] 2017-09-05 16:16
>why doesn't the CodePush server convert 2.3 to 2.3.0 before passing the value to the semver logic? That is what your documentation says and also is a more appropriate behavior for CodePush, don't you think?

CodePush server does not convert 2.3 to 2.3.0 because in case the customer really wants to publish an update that targets to 2.0 - he'll be unable to do that due to the server will convert it to 2.0.0, but customer wants to apply his update to 2.0.x, not to 2.0.0. 
That is the reason why we shouldn't change current logic, otherwise, it will produce unexpected behavior.

To avoid the issue we'll update [Range Expression / Who gets the update](https://github.com/Microsoft/code-push/tree/master/cli#target-binary-version-parameter) table with new row: 1.2 := 1.2.x := >=1.2.0 <1.3.0

Please let me know if you have any other questions.

**Comment by newyankeecodeshop** [comment] 2017-09-05 16:20
I guess my argument is that, if a customer wants to apply his update to 2.0.x, why not require them to publish with `2.0.x`? I agree there is a change in behavior, but the current behavior is less intuitive.
Updating the documentation would be helpful.

**Comment by sergey-akhalkov** [comment] 2017-09-05 16:27
>but the current behavior is less intuitive

Agreed, but it's how the semver works and I believe we should not require from customer to publish 2.0.x instead of 2.0 because CodePush relates on semver and semver [allows both variants](https://github.com/npm/node-semver#advanced-range-syntax).

So I'm closing the issue, please feel free to open or create new in case of any questions or issues. Thank you.

**Closed by sergey-akhalkov** 2017-09-05 16:27 UTC
