### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by adriano-di-giovanni** [Microsoft/code-push#393] opened 2017-02-10 13:37 UTC
I successfully tested CodePush deployments using `code-push release-cordova`.

I have to say I don't like to deploy cordova-platform-specific files (such as cordova.js) together with my `www/` files. Doing this 
* could lead to inconsistencies
* forces my team mates to have cordova and the cordova project on their machine just to deploy an update with code-push.

I then tried to use `code-push release` to deploy my `www/` files only. An error occured:

```
Fail to load resource
file:///data/data/it.spaghettiinteractive.scopapiu/files/codepush/deploy/ve…083c910281714c305ef93a1ab612fb3c24b6596e728e41080a6ee36256c/www/cordova.js
```

Is it mandatory to deploy cordova-platform-specific files? If so, why?

**Comment by sergey-akhalkov** [comment] 2017-02-22 09:25
@adriano-di-giovanni, sorry for slow response.
I don't sure if it is mandatory to deploy cordova-platform-specific files, but I suppose it was designed this way to make preparing update contents and installing an CodePush update package processes easier. Such approach is suitable for most users and helps to avoid possible issues that may have place due to files  in the `myapp/www` folder are prepared and stored in to `myapp/platforms/%platform%/assets/www` folder by Cordova in a different ways both for Android and iOS

**Comment by adriano-di-giovanni** [comment] 2017-02-22 17:42
@sergey-akhalkov I'm pretty sure it's mandatory to deploy cordova-platform-specific files.
I tried to deploy just my files (html, js, css, images) and I got the error I mentioned above. You can try yourself.

I'm happy to be wrong. If so, please tell me how to avoid deploying cordova-platform-specific files.

If they are mandatory, I'd like to stress it's a suboptimal approach because it

* could lead to inconsistencies
* forces my team mates to have cordova and the cordova project on their machine just to deploy an update with code-push
* increases the size of the deployment

Thanks ;)

**Comment by sergey-akhalkov** [comment] 2017-02-27 12:40
@adriano-di-giovanni, I have to clarify, saying 
>I don't sure if it is mandatory to deploy cordova-platform-specific files

I meant that deployment process for Cordova could be probably designed without using cordova-platform-specific files, then I've supposed why cordova-platform-specific files are used in deployment process for now.

You've got this error: 
>Fail to load resource
file:///data/data/it.spaghettiinteractive.scopapiu/files/codepush/deploy/ve…083c910281714c305ef93a1ab612fb3c24b6596e728e41080a6ee36256c/www/cordova.js

due to this logic: https://github.com/Microsoft/cordova-plugin-code-push/blob/master/bin/www/localPackage.js#L40 . After update installation your assets are in `LocalPackage.VersionsDir + "/" + this.packageHash` location. So your `index.html` file referencing to `cordova.js` could not find it due to `cordova.js` file was not deployed. For now I could not see simple solution allows to avoid deploying cordova-platform-specific files and I don't sure if it should be implemented due to it may cause unexpected issues.
I also believe it is convenient to have all client-side files together due to this approach allows users to make hot fixes for plugins js files without releasing new version of the app. This would be helpful for users having plugins implemented themselves.

>could lead to inconsistencies

Could you please clarify what kind of inconsistencies you are talking about?

>forces my team mates to have cordova and the cordova project on their machine just to deploy an update with code-push

As workaround you could share content of `myapp/platforms/%platform%/assets/www` folder, so your team mates would have ability to release updates using vanilla `code-push release` command.

>increases the size of the deployment

Is that really big problem? I could see that my cordova-platform-specific files takes about ~300 KB.

**Comment by sergey-akhalkov** [comment] 2017-03-06 14:51
@adriano-di-giovanni, just a friendly ping.

**Comment by adriano-di-giovanni** [comment] 2017-03-06 16:09
> Could you please clarify what kind of inconsistencies you are talking about?

Say I perform a `cordova platform update` and I forget to update project version in config.xml. A code-push deploy will update cordova.js, leading to an inconsistency between native cordova version and it's javascript counterpart.

> As workaround you could share content of myapp/platforms/%platform%/assets/www folder, so your team mates would have ability to release updates using vanilla code-push release command, but this approach is unsafe due to you have to control differences between you version of myapp/platforms/%platform%/assets/www folder and version of this folder that having your team mates.

As you said, this approach is unsafe. Versioning could make it safer. IMHO that's another drawback of including cordova-platform-specific files in a deployment.

> I could see that my cordova-platform-specific files takes about ~300 KB for sample app (cordova.js and cordova_plugins.js files, cordova-js-src/ and plugins/ folders). Also note that cordova.js file is not contained in each update package due to diffing logic on CodePush server, only files that have been modified will present in CodePush update package and downloaded by the app.

You're right. We can say it's negligible.

Thanks.

**Comment by silhouettes** [comment] 2017-03-06 19:58
Tagging @panarasi as this may be an interesting point (Cordova-specific)

**Comment by sergey-akhalkov** [comment] 2017-03-07 10:17
>Say I perform a cordova platform update and I forget to update project version in config.xml. A code-push deploy will update cordova.js, leading to an inconsistency between native cordova version and it's javascript counterpart.

Agreed, the inconsistency could be here, so we just have to keep it in mind.

>As you said, this approach is unsafe. Versioning could make it safer. IMHO that's another drawback of including cordova-platform-specific files in a deployment.

We can't use `myapp/www` folder for deployment due to its content may be changed by `cordova prepare` command. So such changed files are locate in `myapp/platforms/android/assets/www` folder and used by the app and by CodePush for deployment process. We also not able to use `myapp/www` folder for releasing CodePush updates due to [Cordova Merges feature](http://moduscreate.com/cross-platform-cordova-app-development-with-merges/). So you probably have to install and use Cordova to prepare CodePush updates. Or you just could use provided workaround.

Please let me know if you have any questions, thank you!

**Comment by sergey-akhalkov** [comment] 2017-03-14 10:13
Closing this for now, please feel free to reopen if needed.

**Closed by sergey-akhalkov** 2017-03-14 10:13 UTC
Labels: question, waiting-for-clarification
