### ISSUE TITLE
Deployment does not exist.

### ISSUE THREAD

**Issue by Kerizer** [microsoft/code-push#719] opened 2020-06-05 11:47 UTC
We can not promote bundle from one deployment to another since it returns `Deployment does not exist.` from both CLI and web. 

1. From CLI
<img width="782" alt="Screenshot 2020-06-05 at 14 44 52" src="https://user-images.githubusercontent.com/21887713/83872714-3443f780-a73b-11ea-86ca-47abfb8c2c29.png">

2. From Web UI
![image](https://user-images.githubusercontent.com/21887713/83872818-635a6900-a73b-11ea-819e-8141ad046cc4.png)

My guess it's due to spaces in name and some decoding issue on your side, but it's only a speculation

UPD: `appcenter codepush release` works properly, problem is `promote`

**Comment by andreidubov** [comment] 2020-06-08 11:06
Hi @Kerizer,
Thanks for reporting!

I reproduced your issue, we will start working on it in the near future, thanks for the information.  I will keep you updated.

**Comment by andreidubov** [comment] 2020-06-10 07:57
Hi @Kerizer, 

We fixed it on our side, could you check and confirm that the problem is gone?

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or issues.

**Closed** 2020-06-10 07:57 UTC
Labels: bug
