### ISSUE TITLE
Audiveris How can I solv this FailureFAILURE: Build failed with an exception.  * What went wrong: Execution failed for task ':git_build'. > A problem occurred starting process 'command 'git''

### ISSUE THREAD

**Issue by kutroArt** [microsoft/code-push#679] opened 2019-11-27 14:01 UTC
Thanks so much for filing an issue or feature request! We will address it as soon as we can. Please follow these guidelines:

1. This repository is for the CodePush CLI and management SDK. For issues relating to the CodePush client SDK's, please see:
  * react-native-code-push: https://github.com/Microsoft/react-native-code-push
  * cordova-plugin-code-push: https://github.com/Microsoft/cordova-plugin-code-push
2. In your description, please include the version of `code-push-cli` or `code-push` that you are using.

**Comment by alexandergoncharov** [comment] 2020-03-03 12:34
Hi @kutroArt ,
Thanks for reporting!

Looks like you have issues with `git` commands.
Could you please try to run `git --version ` in a terminal.
If you get an error, then you need to add git in the global PATH.

If all works correctly then please provide more info that helps me to reproduce your issue.

I'm going to close this issue for now. Please feel free to reopen it if you have any questions or provide more info.

**Closed by alexandergoncharov** 2020-03-03 12:34 UTC
Labels: bug, waiting-for-clarification
