### ISSUE TITLE
Binary updates from store are not updating app

### ISSUE THREAD

**Issue by scopsy** [Microsoft/code-push#380] opened 2017-01-31 14:52 UTC
code-push-cli version: 1.12.6-beta

I'm using codepush with ionic application and i'm having a bit of an issue (perhaps with my understanding of the matter).

I uploaded binary version to the store : v1.0.0

Then I release newer version with codepush: v1.0.1
and again for version v1.0.2

Then I created a new binary version 1.1.0 and uploaded it to the store.
However because the Users are currently pointed to the earlier version /<PATH_TO_APP>/<YOUR_RELEASE_FOLDER>/www/index.html

After they download app store update they are still pointed to the old path and won't see the update unless they download the 1.5.0 again from codepush. 

How should I handle these situations ? Why after the user updates from the store he is not automaticly seeing the latest binary update and instead codepush still points to the old app location path ?

**Comment by sergey-akhalkov** [comment] 2017-02-01 13:23
@scopsy, could you please look at https://github.com/Microsoft/cordova-plugin-code-push/issues/196?
You probably have the same issue. I've also wrote https://github.com/Microsoft/cordova-plugin-code-push/issues/207#issuecomment-276648376 describing possible causes and ways to avoid it.
In a nutshell - please make sure you project folder does not contain any `.DS_Store` files and `__MACOSX` folders generated by iOS, also you should probably apply both https://github.com/Microsoft/cordova-plugin-code-push/pull/202 and https://github.com/Microsoft/cordova-plugin-code-push/pull/201

Please let me know if the issue is still reproduces or if you have any question.

**Comment by sergey-akhalkov** [comment] 2017-02-13 10:42
@scopsy, could you please let us know if you still experiencing the issue?

**Comment by sergey-akhalkov** [comment] 2017-02-21 14:05
Closing this for now, please feel free to reopen if needed.

**Closed by sergey-akhalkov** 2017-02-21 14:05 UTC
Labels: investigating
