### ISSUE TITLE
Error 503. The service is unavailable

### ISSUE THREAD

**Issue by JAStanton** [Microsoft/code-push#511] opened 2017-09-11 16:41 UTC
My apps are calling ` https://codepush.azurewebsites.net/updateCheck` (with a string of arguments) and I'm getting a spike of 503's. Just so you're aware :)

**Comment by ajwhite** [comment] 2017-09-11 18:17
We started to see this spike on Sept 9

**Comment by claykohut** [comment] 2017-09-11 20:16
I've been seeing my builds hang / never finish loading on the codepush sync step -- any way I can confirm that its related to this and not something on my end?

**Comment by JAStanton** [comment] 2017-09-11 20:45
@claykohut  My app aborts after N seconds if I don't think codepush will return in time so that my boot process of the app isn't dependent on if CodePush servers are alive. I recommend something similar.

**Comment by claykohut** [comment] 2017-09-11 22:16
How many seconds are you using as N in that case, @JAStanton ?

**Comment by JAStanton** [comment] 2017-09-11 22:23
I wait 5 seconds for the download / apply step. If it doesn't happen by then I let my app continue to boot. I then apply any updates on next app launch.

**Comment by pniko** [comment] 2017-09-12 18:24
Hi @JAStanton, we have been experiencing a few load issues with our production environments. A permanent fix should be implemented over the next 30 days as we finish up the re-architecture of our backend services, but for now we are monitoring the current problems and making adjustments to rectify them.

**Comment by max-mironov** [comment] 2017-09-15 07:30
Hey all, closing this as we don't see any problems with this currently, please let us know if you see this issue again.

**Closed by max-mironov** 2017-09-15 07:30 UTC

**Comment by prayuditb** [comment] 2017-12-18 16:33
Hello everyone, I just got this error today. I use react-native-codepush.

Here is some of my code
```
...
codepush.sync({
      installMode: codepush.InstallMode.IMMEDIATE,
    });


```
12-18 23:27:39.854 13537 15879 I ReactNativeJS: [CodePush] Checking for update.
12-18 23:27:42.298 13537 15879 I ReactNativeJS: [CodePush] An unknown error occurred.
12-18 23:27:42.298 13537 15879 I ReactNativeJS: [CodePush] 503: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
12-18 23:27:42.298 13537 15879 I ReactNativeJS: <HTML><HEAD><TITLE>Service Unavailable</TITLE>
12-18 23:27:42.298 13537 15879 I ReactNativeJS: <META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
12-18 23:27:42.298 13537 15879 I ReactNativeJS: <BODY><h2>Service Unavailable</h2>
12-18 23:27:42.298 13537 15879 I ReactNativeJS: <hr><p>HTTP Error 503. The service is unavailable.</p>
12-18 23:27:42.298 13537 15879 I ReactNativeJS: </BODY></HTML>

```

**Comment by prayuditb** [comment] 2017-12-18 17:12
In my case, I got this error after I terminate release process by pressing `ctrl + c` (because I forgot something) then I push release once again until release creating release success.
```

**Comment by prayuditb** [comment] 2017-12-18 17:20
In my case, I got this error after I terminate release process by pressing `ctrl + c` (because I forgot something). I think this error reproduced by unfinished release process.

To fix this error, you can try clear deployment history by running this command
`appcenter codepush deployment clear -a <ownerName>/<appName> <deploymentName>`

#### Warning, this command will clear all of your release history
hopefully can help

**Comment by sergey-akhalkov** [comment] 2017-12-18 18:20
Hi @prayuditb, please take a look at https://github.com/Microsoft/code-push/issues/547 and let's move the discussion to the one common place.
