### ISSUE TITLE
app add <project> windows <platform> internal server error

### ISSUE THREAD

**Issue by scott108** [Microsoft/code-push#459] opened 2017-06-05 10:02 UTC
When I added app with app add myApp windows react-native, and I got the error message: Internal server error.
It didn't happen in android and ios.

**Comment by sergey-akhalkov** [comment] 2017-06-05 13:16
Hi @scott108, thanks for filling the issue and sorry for the inconvenience - we've started investigation/fixing and we'll let you know if any updates.

**Comment by BretJohnson** [comment] 2017-06-05 17:23
@scott108 Thanks for alerting us to this. We see what the problem is now. We hope to have the fix in place by end of day.

**Comment by BretJohnson** [comment] 2017-06-05 22:18
@scott108 We just deployed the fix for this, which looks good in my testing. Thanks again for letting us know about this problem. Please let us know if you see any other issues or have any other feedback in general, now that CodePush is part of Mobile Center  (since Friday).

**Closed by BretJohnson** 2017-06-05 22:18 UTC

**Comment by rahulrvp** [comment] 2017-11-15 07:24
Hi there, I am facing a similar issue while trying to add a new `react-native` app for `android`.

I tried running this command
```sh
code-push app add SevensAppTest android react-native
```

Received this error in termingal
```sh
[Error]  Internal Server Error
```

**Comment by rahulrvp** [comment] 2017-11-15 08:37
The issue got resolved after doing a logout followed by a login in code-push CLI

Super weird, but that fixed this issue!

**Comment by sergey-akhalkov** [comment] 2017-11-15 08:47
HI @rahulrvp, thanks for reaching us, sorry for the inconvenience, the issue should be fully resolved now, please let us know if it happens again (just in case - try to logout/login if you'll see it again, but it should work now without any issues).
