### ISSUE TITLE
plugin install fails if "cordova-plugin-device" is already installed

### ISSUE THREAD

**Issue by pke** [Microsoft/code-push#248] opened 2016-06-09 15:11 UTC
```
Installing "cordova-plugin-code-push" for android
Dependent plugin "code-push" already installed on android.
Dependent plugin "cordova-plugin-file" already installed on android.
Dependent plugin "cordova-plugin-file-transfer" already installed on android.
Dependent plugin "cordova-plugin-zip" already installed on android.
Dependent plugin "cordova-plugin-dialogs" already installed on android.
Installing "cordova-plugin-device" for android
Failed to install 'cordova-plugin-device':CordovaError: Uh oh!
".......\platforms\android\src\org\apache\cordova\device\Device.java" already exists!
```

Any way to prevent this error from happening?

**Comment by lostintangent** [comment] 2016-06-09 15:31
Hmm, that's interesting. Cordova is clearly detecting plugins that are already installed, so it's odd that it doesn't detect the device plugin before erroneously trying to install it.

Did you possibly remove the add/remove the device plugin at some point, and it was only partially removed? I've seen issues like this before, where the plugins/* content is cleared when removing a plugin, but there were "dangling assets" left behind within a specific platform that caused issues when trying to reinstall the plugin.

Can you try removing and reading the Android platform? That should help determine if my assumption is correct and your project just got into an odd spot.

**Comment by pke** [comment] 2016-06-09 16:22
removing the plugin solved the issue for now. We will see on the other dev machines how they behave.

**Comment by lostintangent** [comment] 2016-06-09 16:28
@pke Removing the CodePush plugin? The issue you're hitting doesn't appear to be a problem with CodePush as opposed to a Cordova/plugman bug, so I'd love to make sure we can unblock you if possible :)

**Comment by lostintangent** [comment] 2016-06-09 16:58
Ah OK I must have misunderstood you, since your other bug implies you didn't remove CodePush. I'm going to close this for now since you're unblocked, but please re-open it if the problem persists. I'm pretty sure the issue is with the Cordova project being "corrupted" and so the best solution is to just re-add platforms to reset the generated native projects.

**Closed by lostintangent** 2016-06-09 16:58 UTC
