### ISSUE TITLE
is Apple rejects the code push app ?

### ISSUE THREAD

**Issue by Rahulsss443** [Microsoft/code-push#486] opened 2017-07-22 10:34 UTC
This is first time i am using any hot code fix SDK in my apps. I did some research and found that apple is rejecting the app because of this SDK. Can anybody tell should i go with the code push on apple store.

I know this is not the right place to ask this question but i am not able get the right answer from any other place.

Thanks.

**Comment by iageoghe** [comment] 2017-07-24 17:08
We are really sorry to hear that your app was rejected. That being said, we know if no known App Store rejections where CodePush has been determined to be the cause. Can you provide us with some more detail please? What did you use to write your app? What 3rd party components or packages did you include with your application? 

Thanks.

**Comment by max-mironov** [comment] 2017-07-26 06:44
@Rahulsss443 - hi, please let us know if you have a chance to look at this.

**Comment by max-mironov** [comment] 2017-08-02 07:57
Closing the issue for now, please let us know if any further questions regarding this. 
Also you could check out the following links where we have discussed similar question:
1) https://github.com/Microsoft/code-push/issues/415
2) https://github.com/Microsoft/react-native-code-push/issues/748

**Closed by max-mironov** 2017-08-02 07:57 UTC
Labels: question
