### ISSUE TITLE
Ability to promote a specific version

### ISSUE THREAD

**Issue by chendo** [Microsoft/code-push#336] opened 2016-10-20 00:32 UTC
We would like the ability to be able to promote a specific version of a deployment to another deployment.

Context:

We have a Staging, Beta and Production deployments but we don't promote between deployments at the moment as promoting uses the latest release. This doesn't work for us as we would want to promote a potentially older Staging release into Beta, and the same for Beta to Production.

**Comment by silhouettes** [comment] 2016-10-20 17:42
This is a dupe of #267 - I will tag you in that issue and close this one! There is definitely interest in doing this, it's just a matter of having enough resources.

**Closed by silhouettes** 2016-10-20 17:42 UTC
