### ISSUE TITLE
Getting started - update not happening

### ISSUE THREAD

**Issue by yogiben** [Microsoft/code-push#302] opened 2016-08-19 17:06 UTC
React Native, Android.

I pushed app to play store.

Updated app to include code push code.

Then I made an arbitrary change in my js code

`code-push release-react bitwala android`

I can't see the changes.

N.B. I was getting some errors so I updated a line to use the deployment key string instead of the variable that was there before.

`new CodePush("XXX", MainApplication.this, BuildConfig.DEBUG)`

**Comment by silhouettes** [comment] 2016-08-19 18:57
Here are some possible reasons why you might not see updates:

* Deployment key mismatch
* App version mismatch
* The app is being rolled back

We can try to figure out what it is by following these debugging steps:

1. Do you see any installs or rollbacks in your deployment history? `code-push deployment history <appName> <deploymentName>`
2. If that doesn't help, what happens when you test it locally with your production key, and view the log output? You can use any log viewer or the `code-push debug` command to see them.

Let me know how it goes!

**Comment by yogiben** [comment] 2016-08-23 11:25
* I've deployed to both environments
* How can I check this? Im'm updating the `versionCode` in `build.gradle` for every release
* I can't see this happening. I just changed a string, so there would be no error

1. No installs or rollbacks for either environment
2.

**Comment by silhouettes** [comment] 2016-08-23 18:04
Okay, so:

1. To view the logs, you'd need to run `code-push debug` while your app is running in an emulator on your machine (it's a run-time log that shows what is happening as sync() is called).
1. To check that your CodePush releases target the correct app versions of your app, look at the `App Version` column of the `deployment history` command, and then check that they match the `versionName` string in your build.gradle.
1. I suspect that the cause of the problem here is that your `versionName` string is not semver-compliant. It needs to be semver-compliant, or at least two dot-separated integers, i.e. `1.0` or `1.0.0`, so that your releases can be targeted correctly. You may see this mentioned in the CodePush logs in step (1).
1. If none of the above address your problem, can you show me the code where you're using CodePush in your app?

**Comment by yogiben** [comment] 2016-08-24 15:55
1. `code-push debug` didn't work with an emulator. 

`[Error]  No Android devices found. Re-run this command after starting one.`

even when `adb devices` correctly shows the emulator.

Logging on my device appears to work. There are no logs other than `Loading JS bundle from "assets://index.android.bundle"`

2. 

`/app/build/gradle` has `versionName "1.0"`

which matches every deployment on both Staging and Production

3. This is unchanged from what was originally generated `1.0`

4. Sure. Should I add you to the repo?

__

My gut feeling is that

**Comment by silhouettes** [comment] 2016-08-24 17:51
Sure thing, if you add me to the repo I'll have a look! The fact that there are no installs, rollbacks, or logs seems to imply that CodePush is not running at all, so I'm wondering if it's some kind of configuration thing.

**Comment by silhouettes** [comment] 2016-08-26 18:47
Hi @yogiben, did you still need help with this? You can also paste the code snippets of where you used CodePush if you'd like. Also, it might be worth looking through the [manual installation steps](https://github.com/Microsoft/react-native-code-push#android-setup) for Android, just in case RNPM didn't work correctly.

**Comment by silhouettes** [comment] 2016-09-06 22:00
Closing this for now, but please re-open the issue if you still need help, or if you are someone else and facing the same problem!

**Closed by silhouettes** 2016-09-06 22:00 UTC
